# Generated by Django 4.1.7 on 2024-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(max_length=255, verbose_name="description"),
        ),
    ]
