# Generated by Django 4.1.7 on 2024-02-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="banner_image",
            field=models.ImageField(
                default="profile_default.png", upload_to="", verbose_name="banner image"
            ),
        ),
    ]
