# Generated by Django 4.1.7 on 2024-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="profile_default.png",
                upload_to="",
                verbose_name="profile photo",
            ),
        ),
    ]
